services:
  postgres:
    image: postgres:16
    container_name: postgres

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: airflow_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d

  airflow-webserver:
    image: apache/airflow:2.9.3
    container_name: airflow-webserver

    depends_on:
      - postgres

    command: webserver

    ports:
      - "8080:8080"

    volumes:
      - ../dags:/opt/airflow/dags

    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://admin:123456@postgres:5432/airflow_db

  airflow-scheduler:
    image: apache/airflow:2.9.3
    container_name: airflow-scheduler

    depends_on:
      - postgres

    command: scheduler

    volumes:
      - ../dags:/opt/airflow/dags

    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://admin:123456@postgres:5432/airflow_db

volumes:
  postgres_data: