services:

  postgres:
    image: postgres:16

    container_name: postgres

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: airflow_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d

  airflow-webserver:
    image: apache/airflow:2.9.3

    ports:
      - "8080:8080"

    volumes:
      - ../dags:/opt/airflow/dags

    environment:
      HOST: postgres
      USER: admin
      PASSWORD: 123456
      DB: airflow_db

  airflow-scheduler:
      image: apache/airflow:2.9.3

      volumes:
        - ../dags:/opt/airflow/dags

      environment:
        HOST: postgres
        USER: admin
        PASSWORD: 123456
        DB: airflow_db
volumes:
  postgres_data: